### ISSUE TITLE
ClassNotFoundException: com.taobao.weex.analyzer.WeexDevOptions

### ISSUE THREAD

**Issue by wypsanity** [bmfe/eros-yanxuan-demo-v2#10]
### 环境信息 
> 例子：
> * 开发平台：windows
> * node 版本：8.12.0
> * npm 版本：6.4.1
> * 调试类型：真机
> * 调试系统版本: android 5.1
> * 开发工具及其版本 android 3.2

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> W/art: 
android studio  有俩个错误的地方
错误地方一：
Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/System.err: java.lang.ClassNotFoundException: com.taobao.weex.analyzer.WeexDevOptions
W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:318)
        at java.lang.Class.forName(Class.java:276)
        at com.benmu.framework.utils.WXAnalyzerDelegate.<init>(WXAnalyzerDelegate.java:54)
        at com.benmu.framework.activity.AbstractWeexActivity.onCreate(AbstractWeexActivity.java:157)
错误地方二：
E/weex: WXEnvironment getAppVersionName Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Application.getPackageManager()' on a null object reference
        at com.taobao.weex.WXEnvironment.getAppVersionName(WXEnvironment.java:142)
        at com.taobao.weex.WXEnvironment.getConfig(WXEnvironment.java:114)
        at com.benmu.framework.BMWXEngine.initConing(BMWXEngine.java:179)
        at com.benmu.framework.BMWXEngine.initialize(BMWXEngine.java:56)
        at com.benmu.framework.BMWXApplication.initWeex(BMWXApplication.java:114)
        at com.benmu.framework.BMWXApplication.onCreate(BMWXApplication.java:38)
        at com.benmu.wx.App.onCreate(App.java:18)

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：

**Comment by ivantree** [comment]
同样的问题

![微信图片_20190426213311](https://user-images.githubusercontent.com/9014680/56811263-ee93da80-686a-11e9-9750-39ee0c918749.jpg)
![微信图片_20190426213318](https://user-images.githubusercontent.com/9014680/56811264-ef2c7100-686a-11e9-8f89-a421f3248d6f.jpg)


package.json：
{
  "name": "eros-template-name",
  "version": "1.0.1-beta.2",
  "description": "a weex project",
  "main": "index.js",
  "keywords": [
    "weex"
  ],
  "author": "Zero<a2192466@163.com>",
  "license": "MIT",
  "dependencies": {
    "eros-widget": "^1.0.1-beta.5",
    "weex-ui": "^0.6.11"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.2",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-transform-runtime": "~6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.22.0",
    "bindingx-parser": "0.0.x",
    "eslint": "^4.17.0",
    "eslint-plugin-html": "^4.0.2",
    "eslint-plugin-vue": "^4.3.0"
  }
}

**Comment by ivantree** [comment]
2019-04-26 21:28:12.841 24078-24078/com.benmu.wx E/weex: WXEnvironment getAppVersionName Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Application.getPackageManager()' on a null object reference
        at com.taobao.weex.WXEnvironment.getAppVersionName(WXEnvironment.java:142)
        at com.taobao.weex.WXEnvironment.getConfig(WXEnvironment.java:114)
        at com.benmu.framework.BMWXEngine.initConing(BMWXEngine.java:179)
        at com.benmu.framework.BMWXEngine.initialize(BMWXEngine.java:56)
        at com.benmu.framework.BMWXApplication.initWeex(BMWXApplication.java:114)
        at com.benmu.framework.BMWXApplication.onCreate(BMWXApplication.java:38)
        at com.benmu.wx.App.onCreate(App.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by ivantree** [comment]
同样的问题，有人解答一下么
